Remove old sims and refactor
LSSTDESC/descwl-shear-sims pull request #142
Opened 2021-05-19 19:19 UTC by esheldon

closes #132

2021-05-19 19:21 UTC, beckermr commented on descwl_shear_sims/artifacts/cosmic_rays.py
> -"""
Can we please keep this provenance?

2021-05-19 19:23 UTC, beckermr requested changes
One comment. Thanks for doing this!

2021-05-19 20:45 UTC, esheldon commented
I'm going to add some additional testing

2021-05-20 01:50 UTC, esheldon commented
we need more tests but I'm ready to merge this

2021-05-20 01:54 UTC, beckermr approved these changes

2021-05-20 01:55 UTC, merged