add support for hex and grid layout for DeblendedGalaxy
LSSTDESC/descwl-shear-sims pull request #191
Opened 2023-04-18 04:16 UTC by mr-superonion

The galaxy number density is determined by the layout for these two cases.

2023-04-18 04:25 UTC, mr-superonion commented
```
/usr/share/miniconda/envs/test/lib/python3.10/site-packages/hexalattice/hexalattice.py:17: in <module>
    matplotlib.use('Qt5Agg')
```
The test does not pass. But this is the problem of hexalattice. Do we want to fork that repo?

2023-04-18 04:29 UTC, mr-superonion commented
It is this commit:
https://github.com/alexkaz2/hexalattice/commit/14bb67cf939c29b9d57e6b11815beea3a46e0218

2023-04-18 15:51 UTC, esheldon commented
Yeah, that's a bug in hexalattice, it shouldn't require that

2023-07-26 14:29 UTC, mr-superonion commented
@esheldon , I think the bug is fixed after the issue in hexalattice is fixed! Could you please review the PR?

2023-07-26 14:49 UTC, esheldon requested changes

2023-07-26 14:49 UTC, esheldon commented on descwl_shear_sims/galaxies.py
> +            print("The area is of the simulation is %.2f arcmin2" % area)
remove print

2023-07-26 14:49 UTC, esheldon commented on descwl_shear_sims/galaxies.py
> +            print("The area is of the simulation is %.2f arcmin2" % area)
remove print

2023-07-26 17:11 UTC, mr-superonion commented
@esheldon , similar problem in stack, I think the problem comes with  `0.2023.29`. For ` 0.2023.28`, I did not see the error in the pytests.

2023-12-01 19:07 UTC, esheldon requested changes
these changes to the defaults are going to break existing configurations, making the code not backward compatible

2023-12-02 21:41 UTC, mr-superonion commented
shall we merge?

2023-12-05 21:57 UTC, merged