Enable users to use different survey setups (pixel_scale, psf_fwhm)
LSSTDESC/descwl-shear-sims pull request #202
Opened 2023-12-08 04:16 UTC by mr-superonion

This PR enable users to use different survey setups. related to https://github.com/LSSTDESC/descwl-shear-sims/issues/188

2023-12-09 09:31 UTC, mr-superonion commented
@esheldon, @beckermr , can you please review this PR? It enable users to use different survey's pixel scales and magnitude zero points.

2023-12-11 22:50 UTC, mr-superonion commented
Hmm, I think I need more tests... now the code can make simulations for two observations (HSC: left, DES, right) with the same input galaxies, but they are not aligned well..
![image](https://github.com/LSSTDESC/descwl-shear-sims/assets/12228372/799c1343-81f8-4da0-b95b-a56be5117c76)

2023-12-11 23:51 UTC, mr-superonion commented
Let me add a test running the ML detection code and check the centroids have the same sky coords or not..

2023-12-12 02:45 UTC, mr-superonion commented
I think now the sky coordinate matched between the two sims:
![image](https://github.com/LSSTDESC/descwl-shear-sims/assets/12228372/43ea422d-060e-4727-a2fa-75923d129f0d)
I would say (again..) this is probably ready to merge...

2023-12-12 15:14 UTC, esheldon requested changes
I like these changes generally.

However, it is really exposing limitations of the design choices we made.  For example the Layout objects are nice, and probably we should have used them from the beginning. Then we would not need to pass around `coadd_dims` everywhere.

It may be we eventually want to do a restructuring around survey objects and layout objects.  That would, for example, make it easy to simulate CCDs where coadd_dims is not relevant.  Also the survey would carry around pixel scale etc.

2023-12-12 16:31 UTC, mr-superonion commented
> make it easy to simulate CCDs where coadd_dims is not relevant.
Thanks!
Hmm, currently, we are using `coadd_dims` and `coadd_pixel_scale`, `sky_orgin` (not implemented, now it is fixed to (`WORLD_ORIGIN`)) passed to `Layout` object to define the galaxy distribution (taking flat-sky approximation). At the same time we are using `coadd_dims` and `pixel_scale` to define the wcs of the coadd image. 

Some possible changes are listed as follows:

- use `coadd_length` in units of arcmin to define the `Layout` object and remove `coadd_dims` from the input.
- change the `make_coadd_dm_wcs(layout, coadd_pixel_scale, coadd_dims)` to output a set of wcs for coadd pathches. 
- enable users to input wcs of single CCD.

2023-12-12 16:38 UTC, esheldon commented
Sorry, I was just discussing these as future possibilities, not for this PR

2023-12-13 15:53 UTC, esheldon commented on descwl_shear_sims/tests/test_pairs.py
> +from descwl_shear_sims.galaxies import make_galaxy_catalog, DEFAULT_FIXED_GAL_CONFIG
Why was this changed?

2023-12-18 15:42 UTC, esheldon approved these changes

2023-12-18 15:42 UTC, merged